[package]
name = 'NineCoinInit'
version = '1.0.0'
upgrade_policy = "immutable"

[addresses]
nine_coin_init = "e3cd31797b9b36ce3cb9617871fb0fa1187d1381aff01b49d72c87f56e27238e"
liquidswap = "e3cd31797b9b36ce3cb9617871fb0fa1187d1381aff01b49d72c87f56e27238e"

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "a2a3bf79b68823287f962bded2abfaefc688e71c"
subdir = "aptos-move/framework/aptos-framework"
