[package]
name = "mvhashmap"
version = "0.1.0"
authors = ["Aptos Labs <opensource@aptoslabs.com>"]
description = "Move hash map"
repository = "https://github.com/aptos-labs/aptos-core"
homepage = "https://aptoslabs.com"
license = "Apache-2.0"
publish = false
edition = "2021"

[dependencies]
anyhow = "1.0.57"
bcs = { git = "https://github.com/aptos-labs/bcs", rev = "2cde3e8446c460cb17b0c1d6bac7e27e964ac169" }
crossbeam = "0.8.1"
dashmap = "5.2.0"

aptos-aggregator = { path = "../aptos-aggregator" }
aptos-types = { path = "../../types" }

[dev-dependencies]
proptest = "1.0.0"
proptest-derive = "0.3.0"
rayon = "1.5.2"
