[package]
name = "aptos-validator-interface"
version = "0.1.0"
authors = ["Aptos Labs <opensource@aptoslabs.com>"]
description = "Defines interfaces between the aptos nodes and local move infrastructure"
repository = "https://github.com/aptos-labs/aptos-core"
homepage = "https://aptoslabs.com"
license = "Apache-2.0"
publish = false
edition = "2021"

[dependencies]
anyhow = "1.0.57"

aptos-config = { path = "../../config" }
aptos-state-view = { path = "../../storage/state-view" }
aptos-types = { path = "../../types" }

aptosdb = { path = "../../storage/aptosdb" }
move-deps = { path = "../move-deps" }
storage-interface = { path = "../../storage/storage-interface" }
