[package]
name = "MarsLand"
version = "0.0.1"

[addresses]
MarsLand = "0x4247110ad8a97ee048756065975e592732ab746af2a757f285a9966da381d90b"

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "a2a3bf79b68823287f962bded2abfaefc688e71c"
subdir = "aptos-move/framework/aptos-framework"