[package]
name = "move-jim"
version = "0.0.0"

[dependencies]
MoveStdlib = { local = "../move-stdlib" }


[dev-dependencies]
MoveStdlib = { local = "../move-stdlib" }


[addresses]
NamedAddr = "0x1213"