[package]
name = "UseAptosToken"
version = "0.0.1"
upgrade_policy = "compatible"

[dependencies.AptosToken]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "a2a3bf79b68823287f962bded2abfaefc688e71c"
subdir = "aptos-move/framework/aptos-token"

[dependencies.MoveStdlib]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "a2a3bf79b68823287f962bded2abfaefc688e71c"
subdir = "aptos-move/framework/move-stdlib"

[addresses]
web3lab = "0x4247110ad8a97ee048756065975e592732ab746af2a757f285a9966da381d90b"
std = "0x1"
aptos_framework = "0x1"
aptos_token = "0x3"
