[package]
name = "Examples"
version = "0.0.1"

[addresses]
hello_blockchain = "_"

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "a2a3bf79b68823287f962bded2abfaefc688e71c"
subdir = "aptos-move/framework/aptos-framework"