[package]
name = "aptos-resource-viewer"
version = "0.1.0"
authors = ["Aptos Labs <opensource@aptoslabs.com>"]
description = "Aptos resource viewer"
repository = "https://github.com/aptos-labs/aptos-core"
homepage = "https://aptoslabs.com"
license = "Apache-2.0"
publish = false
edition = "2021"

[dependencies]
anyhow = "1.0.57"

aptos-types = { path = "../../types" }
aptos-vm = { path = "../../aptos-move/aptos-vm" }

move-deps = { path = "../move-deps", features = ["address32"] }
