[package]
name = "aptos-sdk-builder"
version = "0.1.0"
authors = ["Aptos Labs <opensource@aptoslabs.com>"]
description = "Aptos transaction-builder"
repository = "https://github.com/aptos-labs/aptos-core"
homepage = "https://aptoslabs.com"
license = "Apache-2.0"
publish = false
edition = "2021"

[dependencies]
anyhow = "1.0.57"
bcs = { git = "https://github.com/aptos-labs/bcs", rev = "2cde3e8446c460cb17b0c1d6bac7e27e964ac169" }
heck = "0.3.2"
once_cell = "1.10.0"
regex = "1.5.5"
serde-generate = { git = "https://github.com/aptos-labs/serde-reflection", rev = "839aed62a20ddccf043c08961cfe74875741ccba" }
serde-reflection = { git = "https://github.com/aptos-labs/serde-reflection", rev = "839aed62a20ddccf043c08961cfe74875741ccba" }
serde_yaml = "0.8.24"
structopt = "0.3.21"
textwrap = "0.15.0"

aptos-types = { path = "../../types" }

move-core-types = { git = "https://github.com/move-language/move", rev = "6a32284d6e04ea5bfa5919df9aac2ccb3ffa010e", features = ["address32"] }

[dev-dependencies]
cached-packages = { path = "../../aptos-move/framework/cached-packages" }
framework = { path = "../framework" }
tempfile = "3.3.0"
which = "4.2.5"

[features]
default = []
