[package]
name = "aptos-writeset-generator"
version = "0.1.0"
authors = ["Aptos Labs <opensource@aptoslabs.com>"]
description = "Generating writesets used for incident management"
repository = "https://github.com/aptos-labs/aptos-core"
homepage = "https://aptoslabs.com"
license = "Apache-2.0"
publish = false
edition = "2021"

[dependencies]
anyhow = "1.0.57"
bcs = { git = "https://github.com/aptos-labs/bcs", rev = "2cde3e8446c460cb17b0c1d6bac7e27e964ac169" }
handlebars = "4.2.2"
serde = { version = "1.0.137", default-features = false }
tempfile = "3.3.0"

aptos-crypto = { path = "../../crates/aptos-crypto" }
aptos-crypto-derive = { path = "../../crates/aptos-crypto-derive" }
aptos-gas = { path = "../aptos-gas" }
aptos-state-view = { path = "../../storage/state-view" }
aptos-types = { path = "../../types" }
aptos-vm = { path = "../aptos-vm" }

cached-packages =  { path = "../framework/cached-packages" }
framework =  { path = "../framework" }
move-deps = { path = "../../aptos-move/move-deps", features = ["address32", "table-extension"] }
