[package]
name = "aptos-transactional-test-harness"
version = "0.1.0"
authors = ["Aptos Labs <opensource@aptoslabs.com>"]
description = "Transactional testing framework for Move"
repository = "https://github.com/aptos-labs/aptos-core"
homepage = "https://aptoslabs.com"
license = "Apache-2.0"
publish = false
edition = "2021"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.57"
bcs = { git = "https://github.com/aptos-labs/bcs", rev = "2cde3e8446c460cb17b0c1d6bac7e27e964ac169" }
clap = "3.1.8"
hex = "0.4.3"
once_cell = "1.10.0"
serde = { version = "1.0.137", default-features = false }
serde_json = "1.0.81"

# Move dependencies
move-deps = { path = "../move-deps", features = ["address32"] }

# Aptos Move dependencies
aptos-api-types = { path = "../../api/types" }
aptos-gas = { path = "../aptos-gas" }
aptos-vm =  { path = "../aptos-vm" }
cached-packages =  { path = "../framework/cached-packages" }
framework =  { path = "../framework" }
language-e2e-tests = { path = "../e2e-tests" }
vm-genesis = { path = "../vm-genesis" }

# Other Aptos dependencies
aptos-crypto = { path = "../../crates/aptos-crypto" }
aptos-state-view = { path = "../../storage/state-view" }
aptos-types = { path = "../../types", features = ["fuzzing"] }
storage-interface = { path = "../../storage/storage-interface" }

[dev-dependencies]
datatest-stable = "0.1.1"

[[test]]
name = "tests"
harness = false
