[package]
name = "aptos-transaction-benchmarks"
version = "0.1.0"
authors = ["Aptos Labs <opensource@aptoslabs.com>"]
description = "Aptos transaction benchmarks"
repository = "https://github.com/aptos-labs/aptos-core"
homepage = "https://aptoslabs.com"
license = "Apache-2.0"
publish = false
edition = "2021"

[dependencies]
criterion = "0.3.5"
criterion-cpu-time = "0.1.0"
num_cpus = "1.13.1"
proptest = "1.0.0"

aptos-bitvec = { path = "../../crates/aptos-bitvec" }
aptos-crypto = { path = "../../crates/aptos-crypto" }
aptos-types = { path = "../../types", features = ["fuzzing"] }
aptos-vm = { path = "../aptos-vm" }

language-e2e-tests = { path = "../e2e-tests" }
move-deps = { path = "../../aptos-move/move-deps" }

[[bench]]
name = "transaction_benches"
harness = false
