[package]
name = "vm-genesis"
version = "0.1.0"
edition = "2021"
authors = ["Aptos Labs <opensource@aptoslabs.com>"]
description = "Aptos vm genesis"
repository = "https://github.com/aptos-labs/aptos-core"
homepage = "https://aptoslabs.com"
license = "Apache-2.0"
publish = false

[dependencies]
anyhow = "1.0.57"
bcs = { git = "https://github.com/aptos-labs/bcs", rev = "2cde3e8446c460cb17b0c1d6bac7e27e964ac169" }
once_cell = "1.10.0"
rand = "0.7.3"
serde = { version = "1.0.137", default-features = false }

aptos-crypto = { path = "../../crates/aptos-crypto" }
aptos-gas = { path = "../aptos-gas" }
aptos-state-view = { path = "../../storage/state-view" }
aptos-types = { path = "../../types" }
aptos-vm = { path = "../aptos-vm" }
cached-packages =  { path = "../framework/cached-packages" }
framework =  { path = "../framework" }

move-core-types = { git = "https://github.com/move-language/move", rev = "6a32284d6e04ea5bfa5919df9aac2ccb3ffa010e", features = ["address32"] }
move-vm-types = { git = "https://github.com/move-language/move", rev = "6a32284d6e04ea5bfa5919df9aac2ccb3ffa010e" }

[dev-dependencies]
proptest = "1.0.0"
proptest-derive = "0.3.0"

aptos-proptest-helpers = { path = "../../crates/aptos-proptest-helpers" }

move-core-types = { git = "https://github.com/move-language/move", rev = "6a32284d6e04ea5bfa5919df9aac2ccb3ffa010e", features = ["address32", "fuzzing"] }

[features]
default = []
fuzzing = ["aptos-types/fuzzing", "move-core-types/fuzzing", "move-vm-types/fuzzing"]
